-- INSERT INTO Manufacturer VALUES ('{name}');
INSERT INTO Manufacturer VALUES ('Acura');
INSERT INTO Manufacturer VALUES ('Alfa Romeo');
INSERT INTO Manufacturer VALUES ('Aston Martin');
INSERT INTO Manufacturer VALUES ('Audi');
INSERT INTO Manufacturer VALUES ('Bentley');
INSERT INTO Manufacturer VALUES ('BMW');
INSERT INTO Manufacturer VALUES ('Buick');
INSERT INTO Manufacturer VALUES ('Cadillac');
INSERT INTO Manufacturer VALUES ('Chevrolet');
INSERT INTO Manufacturer VALUES ('Chrysler');
INSERT INTO Manufacturer VALUES ('Dodge');
INSERT INTO Manufacturer VALUES ('Ferrari');
INSERT INTO Manufacturer VALUES ('FIAT');
INSERT INTO Manufacturer VALUES ('Ford');
INSERT INTO Manufacturer VALUES ('Freightliner');
INSERT INTO Manufacturer VALUES ('Genesis');
INSERT INTO Manufacturer VALUES ('GMC');
INSERT INTO Manufacturer VALUES ('Honda');
INSERT INTO Manufacturer VALUES ('Hyundai');
INSERT INTO Manufacturer VALUES ('INFINITI');
INSERT INTO Manufacturer VALUES ('Jaguar');
INSERT INTO Manufacturer VALUES ('Jeep');
INSERT INTO Manufacturer VALUES ('Kia');
INSERT INTO Manufacturer VALUES ('Lamborghini');
INSERT INTO Manufacturer VALUES ('Land Rover');
INSERT INTO Manufacturer VALUES ('Lexus');
INSERT INTO Manufacturer VALUES ('Lincoln');
INSERT INTO Manufacturer VALUES ('Lotus');
INSERT INTO Manufacturer VALUES ('Maserati');
INSERT INTO Manufacturer VALUES ('MAZDA');
INSERT INTO Manufacturer VALUES ('McLaren');
INSERT INTO Manufacturer VALUES ('Mercedes-Benz');
INSERT INTO Manufacturer VALUES ('MINI');
INSERT INTO Manufacturer VALUES ('Mitsubishi');
INSERT INTO Manufacturer VALUES ('Nissan');
INSERT INTO Manufacturer VALUES ('Porsche');
INSERT INTO Manufacturer VALUES ('Ram');
INSERT INTO Manufacturer VALUES ('Rolls-Royce');
INSERT INTO Manufacturer VALUES ('SAAB');
INSERT INTO Manufacturer VALUES ('smart');
INSERT INTO Manufacturer VALUES ('Subaru');
INSERT INTO Manufacturer VALUES ('Tesla');
INSERT INTO Manufacturer VALUES ('Toyota');
INSERT INTO Manufacturer VALUES ('Vauxhall');
INSERT INTO Manufacturer VALUES ('Volkswagen');
INSERT INTO Manufacturer VALUES ('Volvo');
